name: Build, Format, and Analyze

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: calebrjc/avr-gcc-7.3.0:latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Meson
      run: PATH=/home/dev/tools/avr-gcc/bin:$PATH meson setup builddir --cross-file meson/avr-cross.txt

    - name: Build
      run: cd builddir; PATH=/home/dev/tools/avr-gcc/bin:$PATH ninja

    - name: Check formatting
      run: cd builddir; ninja clang-format && git diff --quiet

    - name: Run linting
      run: cd builddir; ninja check
